# ~/.bashrc
# This file is managed by Ansible.

# Exit if not running interactively
if [[ $- != *i* ]] ; then
    return
fi

## Shell configuration

# Keep around sixteen million lines of history in file
HISTFILESIZE=$((2 ** 24))

# Keep around four thousand lines of history in memory
HISTSIZE=$((2 ** 12))

# Ignore duplicate commands and whitespace in history
HISTCONTROL=ignoreboth

# Keep the times of the commands in history
HISTTIMEFORMAT='%F %T '

# Update columns and rows if window size changes
shopt -s checkwinsize

# Force programmable completion features to be enabled
if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    . /usr/share/bash-completion/bash_completion
elif [[ -f /etc/bash_completion ]]; then
    . /etc/bash_completion
fi

## Prompt

# Make root's shell an obvious bright red, all other shells green
if [[ ${EUID} == 0 ]] ; then
    PS1='\[\033[01;31m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
fi

## External tools

# If `lesspipe' is installed, make `less' able to read binaries and things
if [[ -x /usr/bin/lesspipe ]]; then
    eval "$(SHELL=/bin/sh lesspipe)"
fi

# If `dircolors' is installed, make `ls' output colourised
if [[ -x /usr/bin/dircolors ]]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls="ls --color=auto"
fi

# Configure `quilt' for Debian packaging
alias dquilt="quilt --quiltrc=${HOME}/.quiltrc-dpkg"
complete -F _quilt_completion $_quilt_complete_opt dquilt

## Environment

# If an xterm-alike is in use, set the titlebar and force 256 colour mode
case "${TERM}" in
    xterm*|rxvt*)
        PS1="\[\e]0;\u@\h: \w\a\]$PS1"
        export TERM="xterm-256color"
    ;;
    *)
    ;;
esac

# Probably the best editor
export EDITOR="vim"

# Used by dch and other Debian tools
export NAME="Michael Fincham"
export DEBEMAIL="michael@hotplate.co.nz"

# Personal `bin' and `opt'
export PATH="$PATH:$(printf "%s:" ~/opt/*/bin)~/bin"
