- name: kernel IO scheduler to noop
  lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX="((?!.*elevator=.*).*)"$' line='GRUB_CMDLINE_LINUX="\1 elevator=noop"' backrefs=yes
  when: ansible_virtualization_type == "kvm" and ansible_virtualization_role == "guest"
  notify: update-grub
